# Import the libraries

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# Import the dataset

In [92]:
dataset = pd.read_csv("/Data.csv")

In [93]:
dataset

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [94]:
X = dataset.iloc[:,:-1].values
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [95]:
y=dataset.iloc[:,-1].values

In [96]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

# Assignment 1

In [ ]:
# from sklearn.model_selection import train_test_split
# from sklearn.datasets import load_iris

In [ ]:
# data = load_iris()

In [ ]:
# iris= pd.read_csv("/Iris.csv")

In [ ]:
# iris

In [ ]:
# X1=iris.iloc[:,:-1].values
# y1=iris.iloc[:,-1].values

In [ ]:
# print(X1)

In [ ]:
# print(y1)

# Handling Missing Data

In [97]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean');

In [98]:
imputer.fit(X[:,1:3])
X[:,1:3] = imputer.transform(X[:,1:3])

In [99]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]

# Assignment 2

In [56]:
# pima = pd.read_csv("/content/pima-indians-diabetes.csv")
# pima

      6  148  72  35    0  33.6  0.627  50  1
0     1   85  66  29    0  26.6  0.351  31  0
1     8  183  64   0    0  23.3  0.672  32  1
2     1   89  66  23   94  28.1  0.167  21  0
3     0  137  40  35  168  43.1  2.288  33  1
4     5  116  74   0    0  25.6  0.201  30  0
..   ..  ...  ..  ..  ...   ...    ...  .. ..
762  10  101  76  48  180  32.9  0.171  63  0
763   2  122  70  27    0  36.8  0.340  27  0
764   5  121  72  23  112  26.2  0.245  30  0
765   1  126  60   0    0  30.1  0.349  47  1
766   1   93  70  31    0  30.4  0.315  23  0

[767 rows x 9 columns]

In [59]:
# missing_data = pima.isnull().sum()

In [60]:
# print(missing_data)

6        0
148      0
72       0
35       0
0        0
33.6     0
0.627    0
50       0
1        0
dtype: int64

In [62]:
# imputer1 = SimpleImputer(missing_values=np.nan,strategy="mean")
# imputer1.fit(pima)
# pima2 = imputer1.transform(pima)
# print("The updated matrix is:",pima2)

The updated matrix is: [[1.00e+00 8.50e+01 6.60e+01 ... 3.51e-01 3.10e+01 0.00e+00]
 [8.00e+00 1.83e+02 6.40e+01 ... 6.72e-01 3.20e+01 1.00e+00]
 [1.00e+00 8.90e+01 6.60e+01 ... 1.67e-01 2.10e+01 0.00e+00]
 ...
 [5.00e+00 1.21e+02 7.20e+01 ... 2.45e-01 3.00e+01 0.00e+00]
 [1.00e+00 1.26e+02 6.00e+01 ... 3.49e-01 4.70e+01 1.00e+00]
 [1.00e+00 9.30e+01 7.00e+01 ... 3.15e-01 2.30e+01 0.00e+00]]

# Encoding categorical data

# Encoding independent variable

In [100]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [101]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]

# Encoding dependent variable

In [102]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]

# Assignment 3

In [79]:
# df = pd.read_csv("/content/titanic.csv")

In [80]:
# df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [103]:
# import seaborn as sns
# titanic = sns.load_dataset("titanic")

In [84]:
# titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [105]:
# categorical_features=['sex','embarked']
# ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),categorical_features)],remainder='passthrough')
# X3 = np.array(ct.fit_transform(titanic))
# print(X3)

[[0.0 1.0 0.0 ... 'Southampton' 'no' False]
 [1.0 0.0 1.0 ... 'Cherbourg' 'yes' False]
 [1.0 0.0 0.0 ... 'Southampton' 'yes' True]
 ...
 [1.0 0.0 0.0 ... 'Southampton' 'no' False]
 [0.0 1.0 1.0 ... 'Cherbourg' 'yes' True]
 [0.0 1.0 0.0 ... 'Queenstown' 'no' True]]

In [90]:
# le = LabelEncoder()
# y3 = le.fit_transform(df['Survived'])

In [91]:
# print(X3)
# print(y3)

[[0.0 1.0 0.0 ... 'Southampton' 'no' False]
 [1.0 0.0 1.0 ... 'Cherbourg' 'yes' False]
 [1.0 0.0 0.0 ... 'Southampton' 'yes' True]
 ...
 [1.0 0.0 0.0 ... 'Southampton' 'no' False]
 [0.0 1.0 1.0 ... 'Cherbourg' 'yes' True]
 [0.0 1.0 0.0 ... 'Queenstown' 'no' True]]
[0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0
 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0
 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0
 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0
 1 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1
 1 1 1 1 1 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 1 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 1 0 1 1 0 1 1 0 0 1 0
 1 0 1 0 0 1 0 0 1 0 0 0 1 0 0 1 0 1 0 1 0 1 1 0 0 1 0 0 1 1 0 1 1 0 0 1 1
 0 1 0 1 1 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 1 1 0 1 1 1 0 0 0 1 0 1 0 0 0 1
 0 0 0 0 1 0 0 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 0 1 0 0 1 0 0 1 1 0 0 0 0 1 0
 0 1 0 1 0 0 1 0 0 0 0 0 1 0 1 1 1 0 1 0 1 0 1 0 1 0 0 0 0 0 0 1 0 0 0 1 0
 0 0 0 1 1 0 0 1 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 0 0 1 1 0
 0 0 0 1 1 1 1 1 0 1 0 0 0 1 1 0 0 1 0 0 0 1 0 1 1 0 0 1 0 0 0 0 0 0 1 0 0
 1 0 1 0 1 0 0 1 0 0 1 1 0 0 1 1 0 0 0 1 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0
 1 0 1 1 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 1 1 1 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 1 1 1 0 0 0 1 0 0 1 1 0 0 1 0 0 0 0 0 0 1 0
 0 0 1 0 1 1 1 1 0 0 0 1 0 0 1 1 0 0 1 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0 1
 0 1 0]

# Train Test Split

In [114]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2,random_state=1)

In [116]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]

In [117]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]

In [118]:
print(y_train)

[0 1 0 0 1 1 0 1]

In [119]:
print(y_test)

[0 1]

# Feature Scaling

In [120]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,3:] = sc.fit_transform(X_train[:,3:])
X_test[:,3:] = sc.transform(X_test[:,3:])

In [122]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]

In [123]:
print(X_test)

[[0.0 1.0 0.0 -1.0 -1.0]
 [1.0 0.0 0.0 1.0 1.0]]

# Assignment 4

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [4]:
iris= pd.read_csv("/content/Iris.csv")
iris

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [19]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
iris['Species'] = le.fit_transform(iris['Species'])

In [20]:
iris

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]

In [21]:
component_to_delete = ['Species','Id']
X3 = iris.drop(component_to_delete,axis=1)

In [22]:
X3

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [23]:
y3=iris['Species']

In [24]:
y3

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species, Length: 150, dtype: int64

In [25]:
X3_train,X3_test,y3_train,y3_test = train_test_split(X3,y3,test_size=0.2,random_state=42)

In [26]:
print(X3_train)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
22             4.6           3.6            1.0           0.2
15             5.7           4.4            1.5           0.4
65             6.7           3.1            4.4           1.4
11             4.8           3.4            1.6           0.2
42             4.4           3.2            1.3           0.2
..             ...           ...            ...           ...
71             6.1           2.8            4.0           1.3
106            4.9           2.5            4.5           1.7
14             5.8           4.0            1.2           0.2
92             5.8           2.6            4.0           1.2
102            7.1           3.0            5.9           2.1

[120 rows x 4 columns]

In [28]:
print(X3_test)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
73             6.1           2.8            4.7           1.2
18             5.7           3.8            1.7           0.3
118            7.7           2.6            6.9           2.3
78             6.0           2.9            4.5           1.5
76             6.8           2.8            4.8           1.4
31             5.4           3.4            1.5           0.4
64             5.6           2.9            3.6           1.3
141            6.9           3.1            5.1           2.3
68             6.2           2.2            4.5           1.5
82             5.8           2.7            3.9           1.2
110            6.5           3.2            5.1           2.0
12             4.8           3.0            1.4           0.1
36             5.5           3.5            1.3           0.2
9              4.9           3.1            1.5           0.1
19             5.1           3.8            1.5           0.3
56             6.3           3.3            4.7           1.6
104            6.5           3.0            5.8           2.2
69             5.6           2.5            3.9           1.1
55             5.7           2.8            4.5           1.3
132            6.4           2.8            5.6           2.2
29             4.7           3.2            1.6           0.2
127            6.1           3.0            4.9           1.8
26             5.0           3.4            1.6           0.4
128            6.4           2.8            5.6           2.1
131            7.9           3.8            6.4           2.0
145            6.7           3.0            5.2           2.3
108            6.7           2.5            5.8           1.8
143            6.8           3.2            5.9           2.3
45             4.8           3.0            1.4           0.3
30             4.8           3.1            1.6           0.2

In [29]:
print(y3_train)

22     0
15     0
65     1
11     0
42     0
      ..
71     1
106    2
14     0
92     1
102    2
Name: Species, Length: 120, dtype: int64

In [30]:
print(y3_test)

73     1
18     0
118    2
78     1
76     1
31     0
64     1
141    2
68     1
82     1
110    2
12     0
36     0
9      0
19     0
56     1
104    2
69     1
55     1
132    2
29     0
127    2
26     0
128    2
131    2
145    2
108    2
143    2
45     0
30     0
Name: Species, dtype: int64

In [31]:
scaler = StandardScaler()
X3_train = scaler.fit_transform(X3_train)
X3_test = scaler.transform(X3_test)

In [32]:
print(X3_train)

[[-1.47393679  1.22037928 -1.5639872  -1.30948358]
 [-0.13307079  3.02001693 -1.27728011 -1.04292204]
 [ 1.08589829  0.09560575  0.38562104  0.28988568]
 [-1.23014297  0.77046987 -1.21993869 -1.30948358]
 [-1.7177306   0.32056046 -1.39196294 -1.30948358]
 [ 0.59831066 -1.25412249  0.72966956  0.95628954]
 [ 0.72020757  0.32056046  0.44296246  0.42316645]
 [-0.74255534  0.99542457 -1.27728011 -1.30948358]
 [-0.98634915  1.22037928 -1.33462153 -1.30948358]
 [-0.74255534  2.34515281 -1.27728011 -1.44276436]
 [-0.01117388 -0.80421307  0.78701097  0.95628954]
 [ 0.23261993  0.77046987  0.44296246  0.55644722]
 [ 1.08589829  0.09560575  0.5576453   0.42316645]
 [-0.49876152  1.8952434  -1.39196294 -1.04292204]
 [-0.49876152  1.44533399 -1.27728011 -1.30948358]
 [-0.37686461 -1.47907719 -0.01576889 -0.24323741]
 [ 0.59831066 -0.57925837  0.78701097  0.42316645]
 [ 0.72020757  0.09560575  1.01637665  0.82300877]
 [ 0.96400139 -0.12934896  0.38562104  0.28988568]
 [ 1.69538284  1.22037928  1.36042516  1.75597417]
 [-0.13307079 -0.35430366  0.2709382   0.15660491]
 [ 2.18297047 -0.12934896  1.64713226  1.22285108]
 [-0.2549677  -0.12934896  0.44296246  0.42316645]
 [-0.86445224  0.99542457 -1.33462153 -1.30948358]
 [ 2.30486738 -0.57925837  1.70447368  1.08957031]
 [-0.01117388 -0.80421307  0.21359679 -0.24323741]
 [-0.74255534  0.77046987 -1.33462153 -1.30948358]
 [-0.98634915  0.99542457 -1.39196294 -1.17620281]
 [-0.86445224  1.67028869 -1.04791443 -1.04292204]
 [-0.98634915 -2.37889602 -0.13045173 -0.24323741]
 [ 0.59831066 -0.80421307  0.67232814  0.82300877]
 [-1.23014297  0.77046987 -1.04791443 -1.30948358]
 [-0.98634915 -0.12934896 -1.21993869 -1.30948358]
 [-0.86445224  0.54551516 -1.16259727 -0.90964127]
 [-0.2549677  -0.80421307  0.2709382   0.15660491]
 [-0.86445224  0.77046987 -1.27728011 -1.30948358]
 [-0.13307079 -0.12934896  0.2709382   0.02332414]
 [ 2.30486738  1.67028869  1.70447368  1.35613185]
 [-1.47393679  0.32056046 -1.33462153 -1.30948358]
 [ 0.47641375 -0.35430366  0.32827962  0.15660491]
 [-0.13307079 -1.25412249  0.72966956  1.08957031]
 [-0.37686461  2.57010752 -1.33462153 -1.30948358]
 [ 0.23261993 -0.12934896  0.61498672  0.82300877]
 [-0.01117388 -0.80421307  0.78701097  0.95628954]
 [ 0.23261993 -1.9289866   0.15625537 -0.24323741]
 [-0.49876152 -0.12934896  0.44296246  0.42316645]
 [ 0.47641375  0.77046987  0.95903523  1.48941263]
 [-0.37686461 -1.7040319   0.15625537  0.15660491]
 [-0.49876152  1.8952434  -1.16259727 -1.04292204]
 [-0.98634915 -1.7040319  -0.24513457 -0.24323741]
 [ 0.72020757 -0.80421307  0.90169381  0.95628954]
 [-0.98634915  0.54551516 -1.33462153 -1.30948358]
 [-0.98634915  0.32056046 -1.44930436 -1.30948358]
 [-0.37686461 -1.47907719  0.04157253 -0.10995664]
 [ 1.08589829 -0.12934896  0.72966956  0.68972799]
 [-1.10824606  0.09560575 -1.27728011 -1.44276436]
 [-0.01117388 -0.57925837  0.78701097  1.6226934 ]
 [-0.98634915  0.77046987 -1.27728011 -1.30948358]
 [-0.98634915  0.99542457 -1.21993869 -0.7763605 ]
 [ 0.11072303  0.32056046  0.61498672  0.82300877]
 [-0.86445224 -1.25412249 -0.41715882 -0.10995664]
 [ 1.32969211  0.32056046  1.13105949  1.48941263]
 [ 0.23261993 -0.80421307  0.78701097  0.55644722]
 [ 0.35451684 -1.02916778  1.07371807  0.28988568]
 [ 2.30486738 -0.12934896  1.36042516  1.48941263]
 [-0.37686461 -1.25412249  0.15625537  0.15660491]
 [-1.7177306  -0.35430366 -1.33462153 -1.30948358]
 [-1.83962751 -0.12934896 -1.50664578 -1.44276436]
 [ 0.23261993 -1.9289866   0.72966956  0.42316645]
 [ 1.69538284  0.32056046  1.30308374  0.82300877]
 [-1.47393679  0.09560575 -1.27728011 -1.30948358]
 [-0.86445224  0.99542457 -1.33462153 -1.17620281]
 [-1.7177306  -0.12934896 -1.39196294 -1.30948358]
 [ 0.59831066 -1.25412249  0.67232814  0.42316645]
 [ 0.59831066  0.77046987  1.07371807  1.6226934 ]
 [-1.47393679  0.77046987 -1.33462153 -1.17620281]
 [ 1.2077952  -0.12934896  1.01637665  1.22285108]
 [ 0.59831066  0.54551516  1.30308374  1.75597417]
 [-1.35203988  0.32056046 -1.39196294 -1.30948358]
 [ 0.35451684 -0.35430366  0.5576453   0.28988568]
 [ 0.84210448 -0.57925837  0.50030388  0.42316645]
 [ 0.47641375 -0.57925837  0.61498672  0.82300877]
 [ 1.45158902  0.32056046  0.5576453   0.28988568]
 [ 0.72020757  0.32056046  0.90169381  1.48941263]
 [-0.86445224  1.67028869 -1.21993869 -1.30948358]
 [ 1.32969211  0.09560575  0.95903523  1.22285108]
 [ 0.11072303 -0.12934896  0.2709382   0.42316645]
 [ 0.84210448 -0.12934896  0.84435239  1.08957031]
 [-0.13307079 -1.02916778 -0.13045173 -0.24323741]
 [-0.74255534 -0.80421307  0.09891395  0.28988568]
 [ 0.35451684 -0.12934896  0.50030388  0.28988568]
 [-1.5958337  -1.7040319  -1.39196294 -1.17620281]
 [ 0.96400139 -0.35430366  0.50030388  0.15660491]
 [-0.37686461 -1.02916778  0.38562104  0.02332414]
 [-0.62065843  1.44533399 -1.27728011 -1.30948358]
 [-0.2549677  -0.12934896  0.21359679  0.15660491]
 [ 1.81727975 -0.35430366  1.475108    0.82300877]
 [ 1.08589829  0.54551516  1.13105949  1.22285108]
 [-0.86445224  1.44533399 -1.27728011 -1.04292204]
 [-1.10824606 -1.47907719 -0.24513457 -0.24323741]
 [ 1.08589829  0.54551516  1.13105949  1.75597417]
 [ 1.69538284 -0.12934896  1.18840091  0.55644722]
 [-1.10824606  0.09560575 -1.27728011 -1.44276436]
 [ 1.08589829  0.09560575  1.07371807  1.6226934 ]
 [-1.10824606 -0.12934896 -1.33462153 -1.30948358]
 [ 1.32969211  0.09560575  0.67232814  0.42316645]
 [ 1.93917666 -0.57925837  1.36042516  0.95628954]
 [ 0.59831066 -0.35430366  1.07371807  0.82300877]
 [-0.13307079 -0.57925837  0.21359679  0.15660491]
 [ 0.84210448 -0.12934896  1.01637665  0.82300877]
 [ 0.59831066 -1.7040319   0.38562104  0.15660491]
 [ 0.72020757 -0.35430366  0.32827962  0.15660491]
 [-0.2549677  -0.57925837  0.67232814  1.08957031]
 [ 0.11072303 -0.12934896  0.78701097  0.82300877]
 [-0.49876152  0.77046987 -1.16259727 -1.30948358]
 [ 0.35451684 -0.57925837  0.15625537  0.15660491]
 [-1.10824606 -1.25412249  0.44296246  0.68972799]
 [-0.01117388  2.1201981  -1.44930436 -1.30948358]
 [-0.01117388 -1.02916778  0.15625537  0.02332414]
 [ 1.57348593 -0.12934896  1.24574233  1.22285108]]

In [33]:
print(X3_test)

[[ 0.35451684 -0.57925837  0.5576453   0.02332414]
 [-0.13307079  1.67028869 -1.16259727 -1.17620281]
 [ 2.30486738 -1.02916778  1.81915651  1.48941263]
 [ 0.23261993 -0.35430366  0.44296246  0.42316645]
 [ 1.2077952  -0.57925837  0.61498672  0.28988568]
 [-0.49876152  0.77046987 -1.27728011 -1.04292204]
 [-0.2549677  -0.35430366 -0.07311031  0.15660491]
 [ 1.32969211  0.09560575  0.78701097  1.48941263]
 [ 0.47641375 -1.9289866   0.44296246  0.42316645]
 [-0.01117388 -0.80421307  0.09891395  0.02332414]
 [ 0.84210448  0.32056046  0.78701097  1.08957031]
 [-1.23014297 -0.12934896 -1.33462153 -1.44276436]
 [-0.37686461  0.99542457 -1.39196294 -1.30948358]
 [-1.10824606  0.09560575 -1.27728011 -1.44276436]
 [-0.86445224  1.67028869 -1.27728011 -1.17620281]
 [ 0.59831066  0.54551516  0.5576453   0.55644722]
 [ 0.84210448 -0.12934896  1.18840091  1.35613185]
 [-0.2549677  -1.25412249  0.09891395 -0.10995664]
 [-0.13307079 -0.57925837  0.44296246  0.15660491]
 [ 0.72020757 -0.57925837  1.07371807  1.35613185]
 [-1.35203988  0.32056046 -1.21993869 -1.30948358]
 [ 0.35451684 -0.12934896  0.67232814  0.82300877]
 [-0.98634915  0.77046987 -1.21993869 -1.04292204]
 [ 0.72020757 -0.57925837  1.07371807  1.22285108]
 [ 2.5486612   1.67028869  1.53244942  1.08957031]
 [ 1.08589829 -0.12934896  0.84435239  1.48941263]
 [ 1.08589829 -1.25412249  1.18840091  0.82300877]
 [ 1.2077952   0.32056046  1.24574233  1.48941263]
 [-1.23014297 -0.12934896 -1.33462153 -1.17620281]
 [-1.23014297  0.09560575 -1.21993869 -1.30948358]]